vlm_base_config: default_planner.yaml

encoder: "dinov2siglip"
encoder_args: { "version": "google/siglip-base-patch16-224" }
voxel_size: 0.04

pad_obstacles: 1

# detection:
#   module: sam2
#   category_map_file: example_cat_map.json

# TAMP parameters
guarantee_instance_is_reachable: True
plan_with_reachable_instances: True
plan_with_scene_graph: False
scene_graph:
  max_near_distance: 0.3
  min_on_height: 0.05
  max_on_height: 0.2

vlm:
  vlm_option: gpt4
  vlm_context_length: 20  # How long messages sent to the vlm server can be if we are using it
  save_vlm_plan: True
  replanning: False
  sample_strategy: "clip"

task:
  command: "Pick up a basket."